bt_project:
  outputs:
    dev:
      account: BA_DHLEE
      database: dbt_hol_2025_dev
      password: 
      role: dbt_hol_role_dev
      schema: public
      threads: 100
      type: snowflake
      user: dbt_hol_user
      warehouse: vwh_dbt_hol_dev
    prod:
      account: BA_DHLEE
      database: dbt_hol_2025_prod
      password: 
      role: dbt_hol_role_prod
      schema: public
      threads: 100
      type: snowflake
      user: dbt_hol_user
      warehouse: vwh_dbt_hol_prod
  target: dev